export const GET_POSTS = "GET_POSTS"
export const GET_POSTS_OK = "GET_POSTS_OK"
export const GET_POSTS_FAIL = "GET_POSTS_FAIL"

export const GET_SINGLE_POST = "GET_SINGLE_POST"
export const GET_SINGLE_POST_OK = "GET_SINGLE_POST_OK"
export const GET_SINGLE_POST_FAIL = "GET_SINGLE_POST_FAIL"



